on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kelvin-olaiya/latex2pdf@main
      - name: Create or Update CV release
        run: |
          mv main.pdf CV.pdf  
          gh release upload --clobber cv CV.pdf
